[build]
  command = "cd frontend && npm ci && npm run build && cp -r build ../build"
  publish = "build"

[context.production.environment]
  REACT_APP_API_URL = "https://smartspend-backend-ddu6.onrender.com/mypockit"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
