services:
  - type: web
    name: smartspend-backend
    env: java
    rootDir: backend
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/expenseTracker-0.0.1-SNAPSHOT.jar
    plan: free
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: APP_JWT_SECRET
        sync: false
      - key: EMAIL_PROVIDER
        value: smtp
      - key: SPRING_MAIL_HOST
        sync: false
      - key: SPRING_MAIL_PORT
        value: "587"
      - key: SPRING_MAIL_USERNAME
        sync: false
      - key: SPRING_MAIL_PASSWORD
        sync: false
      - key: SPRING_MAIL_FROM_EMAIL
        sync: false
      - key: SPRING_MAIL_FROM_NAME
        value: Expense Tracker
    buildFilter:
      paths:
        - backend/**
